# Model
device: 0

name: hugging_cache/llava-onevision-qwen2-7b-ov
model_name: llava-ov
model_class: llava-ov
small_name: hugging_cache/Qwen2-7B
tokenizer_class: Qwen2Tokenizer
tokenizer_name: hugging_cache/llava-onevision-qwen2-7b-ov
cls_name: hugging_cache/distilbert-base-cased
cls_class: AutoModel
inner_params:
- model.layers.25.mlp.down_proj.weight
- model.layers.25.mlp.up_proj.weight
- model.layers.26.mlp.down_proj.weight
- model.layers.26.mlp.up_proj.weight
- model.layers.27.mlp.down_proj.weight
- model.layers.27.mlp.up_proj.weight


# Method
alg: SERAC_MULTI
lr: 1e-5
edit_lr: 1e-2
seed: 0
lr_lr: 0.0
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
final_eval: True
supervised: False
train_base: False
no_grad_layers: null
soft_weighting: False
checkpoint_grad: False
cross_attend: False
cos: False
freeze: null
square: True
bound_embeds: False
use_all_negatives: False
freeze_cntr: False
dist_heads: 1
lora: null
archive: null

batch_size: 1
model_save_pt: 5000
edit_bs: 1
silent: False
#max_epochs: 1
max_iters: 30000
log_interval: 100
val_interval: 5000
early_stop_patience: 10000
early_stop_key: "loss/total_edit_val"
eval_only: False
half: False
save: False
debug: False
log_errors: False
unlikelihood: True


val_batch_size: 1
accumulate_bs: 1
val_steps: 500
opt: Adam
grad_clip: 100.

# Output
results_dir: ./results

# Multimodal
qformer_checkpoint: null
qformer_name_or_path: null
state_dict_file: null
pretrained_ckpt: null

# image
coco_image: /cpfs/29f69eb5e2e60f26/user/GPT/pretrain/mm_intern/hh/data_zoo/vlkeb/mmkb_images
rephrase_image: /cpfs/29f69eb5e2e60f26/user/GPT/pretrain/mm_intern/hh/data_zoo/vlkeb/mmkb_images